/**
* Challenge
* Services specification.
*
* OpenAPI spec version: 1.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.example.retobootcamp.services.model

/**
 * 
 * @param Items 
 * @param Count 
 * @param ScannedCount 
 */
data class Offices (
    val Items: Array<Office>? = null,
    val Count: Int? = null,
    val ScannedCount: Int? = null
) {
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as Offices

        if (Items != null) {
            if (other.Items == null) return false
            if (!Items.contentEquals(other.Items)) return false
        } else if (other.Items != null) return false
        if (Count != other.Count) return false
        if (ScannedCount != other.ScannedCount) return false

        return true
    }

    override fun hashCode(): Int {
        var result = Items?.contentHashCode() ?: 0
        result = 31 * result + (Count ?: 0)
        result = 31 * result + (ScannedCount ?: 0)
        return result
    }
}

