/**
* Challenge
* Services specification.
*
* OpenAPI spec version: 1.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.example.retobootcamp.services.model


/**
 * 
 * @param IdOficina 
 * @param Nombre 
 * @param Ciudad 
 * @param Longitud 
 * @param Latitud 
 */
data class Office (
    val IdOficina: Int? = null,
    val Nombre: String? = null,
    val Ciudad: String? = null,
    val Longitud: String? = null,
    val Latitud: String? = null
)

